os:
  - osx
language: ruby
gemfile:
  - gemfiles/Gemfile.xcodeproj-1.3.x
  - gemfiles/Gemfile.xcodeproj-1.4.x
  - gemfiles/Gemfile.xcodeproj-edge
rvm:
  # The latest ruby version
  - 2.4.0
  # OS X 10.9.5-10.10.0 (2.0.0-p481)
  - 2.0.0-p481
  # OS X 10.9.3-10.9.4
  - 2.0.0-p451
  # OS X 10.9.0-10.9.2
  # TODO currently unavailable: https://github.com/travis-ci/travis-ci/issues/2918
  # - 2.0.0-p247
before_install: gem install bundler -v 1.10.6
